interface BrawlerImageMap {
    [key: string]: string;
  }
  
  export const BrawlerImageMap: BrawlerImageMap = {
    shelly: '/brawlers/shelly.png',
    colt: '/brawlers/colt.png',
    bull: '/brawlers/bull.png',
    brock: '/brawlers/brock.png',
    rico: '/brawlers/rico.png',
    spike: '/brawlers/spike.png',
    barley: '/brawlers/barley.png',
    jessie: '/brawlers/jessie.png',
    nita: '/brawlers/nita.png',
    dynamike: '/brawlers/dynamike.png',
    "el primo": '/brawlers/el-primo.png',
    mortis: '/brawlers/mortis.png',
    crow: '/brawlers/crow.png',
    poco: '/brawlers/poco.png',
    bo: '/brawlers/bo.png',
    piper: '/brawlers/piper.png',
    pam: '/brawlers/pam.png',
    tara: '/brawlers/tara.png',
    darryl: '/brawlers/darryl.png',
    penny: '/brawlers/penny.png',
    frank: '/brawlers/frank.png',
    gene: '/brawlers/gene.png',
    tick: '/brawlers/tick.png',
    leon: '/brawlers/leon.png',
    rosa: '/brawlers/rosa.png',
    carl: '/brawlers/carl.png',
    bibi: '/brawlers/bibi.png',
    '8-bit': '/brawlers/8bit.png',
    sandy: '/brawlers/sandy.png',
    bea: '/brawlers/bea.png',
    emz: '/brawlers/emz.png',
    'mr. p': '/brawlers/mrp.png',
    max: '/brawlers/max.png',
    jacky: '/brawlers/jacky.png',
    gale: '/brawlers/gale.png',
    nani: '/brawlers/nani.png',
    sprout: '/brawlers/sprout.png',
    surge: '/brawlers/surge.png',
    colette: '/brawlers/colette.png',
    amber: '/brawlers/amber.png',
    lou: '/brawlers/lou.png',
    byron: '/brawlers/byron.png',
    edgar: '/brawlers/edgar.png',
    ruffs: '/brawlers/ruffs.png',
    stu: '/brawlers/stu.png',
    belle: '/brawlers/belle.png',
    squeak: '/brawlers/squeak.png',
    grom: '/brawlers/grom.png',
    buzz: '/brawlers/buzz.png',
    griff: '/brawlers/griff.png',
    ash: '/brawlers/ash.png',
    meg: '/brawlers/meg.png',
    lola: '/brawlers/lola.png',
    fang: '/brawlers/fang.png',
    eve: '/brawlers/eve.png',
    janet: '/brawlers/janet.png',
    bonnie: '/brawlers/bonnie.png',
    otis: '/brawlers/otis.png',
    sam: '/brawlers/sam.png',
    gus: '/brawlers/gus.png',
    buster: '/brawlers/buster.png',
    chester: '/brawlers/chester.png',
    gray: '/brawlers/gray.png',
    mandy: '/brawlers/mandy.png',
    'r-t': '/brawlers/rt.png',
    willow: '/brawlers/willow.png',
    maisie: '/brawlers/maisie.png',
    hank: '/brawlers/hank.png',
    cordelius: '/brawlers/cordelius.png',
    doug: '/brawlers/doug.png',
    pearl: '/brawlers/pearl.png',
    chuck: '/brawlers/chuck.png',
    charlie: '/brawlers/charlie.png',
    mico: '/brawlers/mico.png',
    kit: '/brawlers/kit.png',
    'larry & lawrie': '/brawlers/larryandlawrie.png',
    melodie: '/brawlers/melodie.png',
    angelo: '/brawlers/angelo.png',
    draco: '/brawlers/draco.png',
    lily: '/brawlers/lily.png',
    berry: '/brawlers/berry.png',
    clancy: '/brawlers/clancy.png',
    moe: '/brawlers/moe.png',
    kenji: '/brawlers/kenji.png',
    shade: '/brawlers/shade.png',
    juju: '/brawlers/juju.png',
    meeple: '/brawlers/meeple.png',
    ollie: '/brawlers/ollie.png'
  };
  