export const mapImages = {
//Bounty
    'Canal Grande' : '/modes/Bounty/Canal_Grande.webp',
    Hideout : '/modes/Bounty/Hideout.webp',
    'Layer Cake' : '/modes/Bounty/Layer_Cake.webp',
    'No Excuses' : '/modes/Bounty/No_Excuses.webp',
    'Shooting Star' : '/modes/Bounty/Shooting_Star.webp',
    'Snake Prairie' : '/modes/Bounty/Snake_Prairie.webp',
//Brawl Ball
    'Backyard Bowl' : '/modes/Brawl_Ball/Backyard_Bowl.webp',
    'Beach Ball' : '/modes/Brawl_Ball/Beach_Ball.webp',
    'Center Stage' : '/modes/Brawl_Ball/Center_Stage.webp',
    'Penalty Kick' : '/modes/Brawl_Ball/Penalty_Kick.webp',
    'Pinball Dreams' : '/modes/Brawl_Ball/Pinball_Dreams.webp',
    'Pinhole Punt' : '/modes/Brawl_Ball/Pinhole_Punt.webp',
    'Second Try' : '/modes/Brawl_Ball/Second_Try.webp',
    'Sneaky Fields' : '/modes/Brawl_Ball/Sneaky_Fields.webp',
    'Sunny Soccer' : '/modes/Brawl_Ball/Sunny_Soccer.webp',
    'Super Beach' : '/modes/Brawl_Ball/Super_Beach.webp',
    'Trickey' : '/modes/Brawl_Ball/Trickey.webp',
    'Triple Dribble' : '/modes/Brawl_Ball/Triple_Dribble.webp',
//Brawl Ball 5v5
    'Cool Shapes' : '/modes/Brawl_Ball_5v5/Cool_Shapes.webp',
    'Freezing Ripples' : '/modes/Brawl_Ball_5v5/Freezing_Ripples.webp',
    'Great Waves' : '/modes/Brawl_Ball_5v5/Great_Waves.webp',
    Suspenders : '/modes/Brawl_Ball_5v5/Suspenders.webp',
//Duels
    'Monkey Maze' : '/modes/Duels/Monkey_Maze.webp',
    'No Surrender'  : '/modes/Duels/No_Surrender.webp',
    'Petticoat Duel' : '/modes/Duels/Petticoat_Duel.webp',
    'Shrouding Serpent' : '/modes/Duels/Shrouding_Serpent.webp',
    'Warriors Way' : '/modes/Duels/Warriors_Way.webp',
    'Zen Garden' : '/modes/Duels/Zen_Garden.webp',
//Duo Showdown/ Solo Showdown
    'Acid Lakes' : '/modes/Duo_Showdown/Acid_Lakes.webp',
    'Cavern Churn' : '/modes/Duo_Showdown/Cavern_Churn.webp',
    'Dark Passage' : '/modes/Duo_Showdown/Dark_Passage.webp',
    'Double Trouble' : '/modes/Duo_Showdown/Double_Trouble.webp',
    'Dried Up River' : '/modes/Duo_Showdown/Dried_Up_River.webp',
    'Feast Or Famine' : '/modes/Duo_Showdown/Feast_Or_Famine.webp',
    'Final Four' : '/modes/Duo_Showdown/Final_Four.webp',
    'Flying Fantasies' : '/modes/Duo_Showdown/Flying_Fantasies.webp',
    'Island Invasion' : '/modes/Duo_Showdown/Island_Invasion.webp',
    'Marksmans Paradise' : '/modes/Duo_Showdown/Marksmans_Paradise.webp',
    'Rockwall Brawl' : '/modes/Duo_Showdown/Rockwall_Brawl.webp',
    'Safety Center' : '/modes/Duo_Showdown/Safety_Center.webp',
    'Skull Creek' : '/modes/Duo_Showdown/Skull_Creek.webp',
//Gem Grab
    'Crystal Arcade' : '/modes/Gem_Grab/Crystal_Arcade.webp',
    'Deathcap Trap' : '/modes/Gem_Grab/Deathcap_Trap.webp',
    'Double Swoosh' : '/modes/Gem_Grab/Double_Swoosh.webp',
    'Forest Clearing' : '/modes/Gem_Grab/Forest_Clearing.webp',
    'Gem Fort' : '/modes/Gem_Grab/Gem_Fort.webp',
    'Hard Rock Mine' : '/modes/Gem_Grab/Hard_Rock_Mine.webp',
    'Last Stop' : '/modes/Gem_Grab/Last_Stop.webp',
    'Minecart Madness' : '/modes/Gem_Grab/Minecart_Madness.webp',
    'Open Space' : '/modes/Gem_Grab/Open_Space.webp',
    'Rustic Arcade' : '/modes/Gem_Grab/Rustic_Arcade.webp',
    'The Cooler Hard Rock' : '/modes/Gem_Grab/The_Cooler_Hard_Rock.webp',
    'Undermine' : '/modes/Gem_Grab/Undermine.webp', 
//Heist
    'Gg 2.0' : '/modes/Heist/Gg_2.0.webp',
    'Hot Potato' : '/modes/Heist/Hot_Potato.webp',
    'Kaboom Canyon' : '/modes/Heist/Kaboom_Canyon.webp',
    'Safe Zone' : '/modes/Heist/Safe_Zone.webp',
    'Safer(r) Zone' : '/modes/Heist/Safer(r)_Zone.webp',
    'The Great Lake' : '/modes/Heist/The_Great_Lake.webp',
    'Bridge Too Far' : '/modes/Heist/Bridge_Too_Far.webp',
//Hot Zone
    'Dueling Beetles' : '/modes/Hot_Zone/Dueling_Beetles.png',
    'Noisy Neighbors' : '/modes/Hot_Zone/Noisy_Neighbors.png',
    'Open Business' : '/modes/Hot_Zone/Open_Business.png',
    'Parallel Plays' : '/modes/Hot_Zone/Parallel_Plays.png',
    'Ring Of Fire' : '/modes/Hot_Zone/Ring_Of_Fire.png',
    'Watersport' : '/modes/Hot_Zone/Watersport.png',
//Knockout
    'Belle\'s Rock' : '/modes/Knockout/Belles_Rock.webp',
    'Deep Forest' : '/modes/Knockout/Deep_Forest.webp',
    'Flaring Phoenix' : '/modes/Knockout/Flaring_Phoenix.webp',
    'Four Levels' : '/modes/Knockout/Four_Levels.webp',
    'Goldarm Gulch' : '/modes/Knockout/Goldarm_Gulch.webp',
    'H For...'  : '/modes/Knockout/H_For....webp',
    'New Horizons' : '/modes/Knockout/New_Horizons.webp',
    'Out in the Open' : '/modes/Knockout/Out_In_The_Open.webp',
    'Overgrown Ruins' : '/modes/Knockout/Overgrown_Ruins.webp',
    'Temple Of Vroom' : '/modes/Knockout/Temple_Of_Vroom.webp',
    'Tiny Islands' : '/modes/Knockout/Tiny_Islands.webp',
    'Two Rivers' : '/modes/Knockout/Two_Rivers.webp',
//Wipeout
    'Infinite Doom' : '/modes/Wipeout/Infinite_Doom.webp',
    'Layer Bake' : '/modes/Wipeout/Layer_Bake.webp',
    'Quad Damage' : '/modes/Wipeout/Quad_Damage.webp',
    'Slayers Paradise' : '/modes/Wipeout/Slayers_Paradise.webp',
    'Spice Production' : '/modes/Wipeout/Spice_Production.webp',
    'The Great Open' : '/modes/Wipeout/The_Great_Open.webp',
//Wipeout 5v5
    'Frosty Tracks' : '/modes/Wipeout_5v5/Frosty_Tracks.webp',
    'Icy Ice Park' : '/modes/Wipeout_5v5/Icy_Ice_Park.webp',
    'Riverbank Crossing' : '/modes/Wipeout_5v5/Riverbank_Crossing.webp',
    'Slippery Road' : '/modes/Wipeout_5v5/Slippery_Road.webp',
}